### ISSUE TITLE
Week 1: Wireframes / HTML / CSS

### ISSUE THREAD

**Issue by evanfrawley** [TeamMoodGitHub/MarkYang-Term-1#1]
Project: Financial tracking software for student organization 💰 

Now, I understand you're already building this with Flask / Python / SQLAlchemy, but I really think that the game plan that you all have is over complicating stuff... That being said, let's try to learn from the ground up with how I learned web development!

1. _**Wireframes**_ - Understanding what the site will (generally) look like. When coding up something, it is *much* easier to create it with something to work off of -- even though often times these designs won't look exactly like the final version, nor will be super flushed out. Regardless, they're still super useful to use!
2. _**HMTL / CSS**_ - Researching & understanding how HTML / CSS work. This is the bread and butter of websites (and we'll start exploring Javascript next week). I want you to take some time to learn how HTML / CSS work, and how you can go about constructing a webpage from scratch using them!

So here are your action items to complete this week:
- [x] Create initial barebones designs ("wireframes") of all the "views" (individual pages) that you think your site would have. You can create wireframes using [Balsamiq](https://balsamiq.com/) for free!
- [x] Do some HTML / CSS tutorial(s). I'd recommend doing this [one](https://www.codecademy.com/learn/web) and working through enough until you're comfortable with HTML & CSS and have a solid understanding with how they work

Next week I'll have you play around with Javascript to see how you can make your site interactive! Stay tuned for more info on that this week :100:

With this -- GLHF! :fire: Please feel free to reach out to me if you have questions about any of the above 😄  I can't wait to see this site take form, and have you be able to use it by the end, making all of your student body have the financials in line!

**Comment by markkyaw** [comment]
This week, I learned a lot about how HTML and CSS works via Codecademy. I know how they work but I'm not very proficient in using them to code just yet. So, to practice my understanding and ability, I'll be trying to code the HTML pages of the layout of the website that I'm trying to build. The following are some sketches i made via Balsamiq of the site. Through coding with HTML and CSS, i might be able to come up with better designs and what not.
Also, I'll be looking into how to use GitHub proficiently and hopefully I'll be able to do basic github commands by end of this week.
![asg](https://user-images.githubusercontent.com/30735477/29548356-fda8ec70-86b4-11e7-98ee-d3377c7e6fc7.PNG)
![bnf](https://user-images.githubusercontent.com/30735477/29548357-fda97cbc-86b4-11e7-8d41-0cb7d9ec292f.PNG)
![dashboard](https://user-images.githubusercontent.com/30735477/29548358-fda9b5c4-86b4-11e7-8bfa-9b6c02125b4d.PNG)
![edit](https://user-images.githubusercontent.com/30735477/29548360-fdaa1b68-86b4-11e7-890c-00dcbcb64c9c.PNG)
![track](https://user-images.githubusercontent.com/30735477/29548359-fdaa18a2-86b4-11e7-9626-0fa2c06417d8.PNG)
